version: '3.4'
services:
  db:
    image: localhost:5000/mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "AWS_MONGO_CORES"
    environment:
      MONGO_INITDB_ROOT_USERNAME: openstudio
      MONGO_INITDB_ROOT_PASSWORD: openstudio
  queue:
    image: redis:6.0.9
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
    command: "redis-server --requirepass openstudio"

  web:
    image: localhost:5000/openstudio-server
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=AWS_OS_SERVER_NUMBER_OF_WORKERS
      - MAX_REQUESTS=AWS_MAX_REQUESTS
      - MAX_POOL=AWS_MAX_POOL
      - REDIS_URL=redis://:openstudio@queue:6379
      - MONGO_USER=openstudio
      - MONGO_PASSWORD=openstudio
      - QUEUES=analysis_wrappers
      - SECRET_KEY_BASE=e28bb11989e51a155853d18944b3c20acc23f2d0a341261dd8e3fbb3a7689f8aa2ece6c70b716af7fe5b257852361c14e7148525271d6aaf59f785899c3c540a
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
      - queue
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "AWS_WEB_CORES"
    command: /usr/local/bin/start-server
  web-background:
    image: localhost:5000/openstudio-server
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=AWS_OS_SERVER_NUMBER_OF_WORKERS
      - QUEUES=background,analyses
      - REDIS_URL=redis://:openstudio@queue:6379
      - MONGO_USER=openstudio
      - MONGO_PASSWORD=openstudio
      - SECRET_KEY_BASE=e28bb11989e51a155853d18944b3c20acc23f2d0a341261dd8e3fbb3a7689f8aa2ece6c70b716af7fe5b257852361c14e7148525271d6aaf59f785899c3c540a
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
      - web
      - queue
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
    command: /usr/local/bin/start-web-background
  worker:
    image: localhost:5000/openstudio-server
    environment:
      - QUEUES=simulations
      - COUNT=1
      - REDIS_URL=redis://:openstudio@queue:6379
      - MONGO_USER=openstudio
      - MONGO_PASSWORD=openstudio
      - SECRET_KEY_BASE=e28bb11989e51a155853d18944b3c20acc23f2d0a341261dd8e3fbb3a7689f8aa2ece6c70b716af7fe5b257852361c14e7148525271d6aaf59f785899c3c540a
    volumes:
      - /mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
      - queue
      - rserve
    deploy:
      endpoint_mode: dnsrr
      resources:
        reservations:
          cpus: "1"
    command: /usr/local/bin/start-workers
  rserve:
    image: localhost:5000/openstudio-rserve
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
    environment:
      - REDIS_URL=redis://:openstudio@queue:6379
      - MONGO_USER=openstudio
      - MONGO_PASSWORD=openstudio
      - SECRET_KEY_BASE=e28bb11989e51a155853d18944b3c20acc23f2d0a341261dd8e3fbb3a7689f8aa2ece6c70b716af7fe5b257852361c14e7148525271d6aaf59f785899c3c540a
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
volumes:
  osdata:
    external: true
  dbdata:
    external: true
networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
